<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ladeco.Diag.Domain\Ladeco.Diag.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
  </ItemGroup>
</Project>
