<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained Condition="'$(RuntimeIdentifier)' != ''">true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <UseXamlCompilerExecutable>false</UseXamlCompilerExecutable>
    <AssemblyName>LadecoDiag</AssemblyName>
    <Version>1.0.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <ApplicationIcon>Resources\Images\Logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250907003" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ladeco.Diag.Application\Ladeco.Diag.Application.csproj" />
    <ProjectReference Include="..\Ladeco.Diag.Domain\Ladeco.Diag.Domain.csproj" />
    <ProjectReference Include="..\Ladeco.Diag.Infrastructure\Ladeco.Diag.Infrastructure.csproj" />
    <ProjectReference Include="..\Ladeco.Diag.Reporting\Ladeco.Diag.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Page Remove="Resources\Themes\Colors.xaml" />
    <Page Remove="Resources\Themes\LightTheme.xaml" />
    <Page Remove="Resources\Themes\DarkTheme.xaml" />
    <None Include="Resources\Themes\Colors.xaml" />
    <None Include="Resources\Themes\LightTheme.xaml" />
    <None Include="Resources\Themes\DarkTheme.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Images\Logo.png" />
  </ItemGroup>
</Project>
